/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/login-page': RouteRecordInfo<'/auth/login-page', '/auth/login-page', Record<never, never>, Record<never, never>>,
    '/users/components/form/user-create-page': RouteRecordInfo<'/users/components/form/user-create-page', '/users/components/form/user-create-page', Record<never, never>, Record<never, never>>,
    '/users/components/table/user-delete-dialog': RouteRecordInfo<'/users/components/table/user-delete-dialog', '/users/components/table/user-delete-dialog', Record<never, never>, Record<never, never>>,
    '/users/components/table/user-edit-dialog': RouteRecordInfo<'/users/components/table/user-edit-dialog', '/users/components/table/user-edit-dialog', Record<never, never>, Record<never, never>>,
    '/users/components/table/user-table': RouteRecordInfo<'/users/components/table/user-table', '/users/components/table/user-table', Record<never, never>, Record<never, never>>,
    '/users/header-page': RouteRecordInfo<'/users/header-page', '/users/header-page', Record<never, never>, Record<never, never>>,
    '/users/user-page': RouteRecordInfo<'/users/user-page', '/users/user-page', Record<never, never>, Record<never, never>>,
  }
}
